### ISSUE TITLE
Discord data notes

### ISSUE THREAD

**Issue by clemp** [DiamondDAO/discord-bot#1]
Using this thread to post notes, observations, and questions about the Discord data after reviewing the sample in the [/data](https://github.com/DiamondDAO/discord-bot/tree/main/data) folder.

## Metrics for the MVP
1. `community tenure` - for Discord this is the time difference between a member's Discord join date and current date
2. `discord roles` - how many roles are assigned to each member, and which roles are assigned to each member?
3. `member growth` - number of members each day since server inception?

## Questions about the data
1. What is the time frame that a single JSON blob represents? Do we see a history of transactions or only the latest state of the server in a single JSON blob that's returned?
2. How can we get text for some of the fields that only have an id? For example:

```
"roles": [
		"896568153914605618",
		"909603362952069170"
	]
```
We need to have text that describes what `896568153914605618` or `909603362952069170` refer to.

3. What is the difference between `joinedTimestamp` and `createdTimestamp` ?

**Comment by nathankoerschner** [comment]
1. I have been designing to write to a single JSON file, then update that file as new events come in. Would it be advantageous to break this down into separate chunks? 
2. In the example given there, those id's are for roles, of which each Guild has data on. So with those we would look for `Guild.roles['id'] == "896568153914605618"`, and match it with that role. In my mind this will be implemented in the JSON -> DB parser program.
3. `joinedTimestamp` is an attribute of members (when they joined the server), `createdTimestamp` is an attribute of `message` type events (users joining, regular messages, etc)

**Comment by liminal-dog** [comment]
Some other metrics that would be relevant, per member:
- Whether they've exited the server
- how many messages they've sent in each channel
- who they've replied to and how many times
- who they've tagged and how many times

**Comment by clemp** [comment]
## Next steps

1. Identify what the `entity` and `event` data structures for Discord data 
2. Decide on a storage schema for raw data
3. Produce and store raw `entity` and `event` data for Diamond DAO Discord server created by the bot
4. First pass at transforming raw data into the metrics (any programming language - will go into document database eventually)

**Comment by nathankoerschner** [comment]
1. Established, [see data model here (figma)](https://www.figma.com/file/9mLUcexaC5NmLgA8BUSyp4/Discord-Data-Model?node-id=0%3A1). 
2. Established on local machine, currently addressing for S3 at #2 
3. Same as above.
