### ISSUE TITLE
Update paths so that this function writes to S3 instead of local folders

### ISSUE THREAD

**Issue by clemp** [DiamondDAO/discord-bot#2]
Once this solution is deployed on EC2, we need to ensure that the files write to S3 buckets instead of local folders.

Various places in the code current hard code local paths.

https://github.com/DiamondDAO/discord-bot/blob/8d4e2db9f968d9dab9155b679093a83e66438eca/events/guildCreate.js#L28-L36

**Comment by clemp** [comment]
An example of how @alexkeating did this for the Daohaus data pipeline is here:

https://github.com/DiamondDAO/Chainverse/blob/b3b6400628f7b078a59f437a872206f0a63e2ac0/consumer/consumer/main.py#L65-L73

Also here:

https://github.com/DiamondDAO/Chainverse/blob/b3b6400628f7b078a59f437a872206f0a63e2ac0/consumer/consumer/common/s3.py

**Comment by nathankoerschner** [comment]
Completed! See #3 for details. 

Learned how to write data to AWS buckets ✅

**Comment by clemp** [comment]
@nathanabram is there a commit to this repo that shows where you changed the code to write to S3?

**Comment by nathankoerschner** [comment]
> @nathanabram is there a commit to this repo that shows where you changed the code to write to S3?

Yes it's [here](https://github.com/DiamondDAO/discord-bot/commit/462f590076a81a6e1a865bca5212da954a7cae59).

**Comment by clemp** [comment]
@nathanabram walked me through deployment and confirmed that the solution writes to S3 buckets as intended.
