### ISSUE TITLE
Need to design S3 folder structure and update code to match

### ISSUE THREAD

**Issue by clemp** [DiamondDAO/discord-bot#3]
During development the folder structure was designed for local folders. Need to confirm that this folder structure will work with S3.

Top level S3 buckets are:

- `chainverse\discord\guilds\`
- `chainverse\discord\users\`

Need to confirm that new information generated by the bot will fit into this design.

**Comment by nathankoerschner** [comment]
Designed as above. For a guild with `$guildID`, there will be `chainverse/discord/guilds/$guildID/`, which will have, according to the datamodel,

- `channels/`
- `members/`
- `roles/`
- `messages/`
- `reactions/`

Within each of these entity directories, there will be entity records named `_$DiscordUID_$Timestamp`, and event records named `$eventName_$DiscordUID_$Timestamp`. Events that correspond to the creation of a new entity (such as channelCreate, memberJoin, or reactionAdd) simply output the entity record.

Discord only exposes reactions via events (they do not have their own UIDs), so reaction entities are titled `_$ReactedMessageUID_$Timestamp`. Each unique reaction should be given a UID when parsed into the DB.
